### ISSUE TITLE
Controller support  // Cyberpunk 2077

### ISSUE THREAD

**Issue by vertex** [Steam-Headless/docker-steam-headless#10]
I'm trying to run Cyberpunk 2077 from a Steam deck, but cyberpunk makes a keyboard assumption. 

When I try to stream it from my PC however, Cyberpunk sees the Steam Deck as a controller.

I figured I'd post an issue here to see if anyone has any ideas?

**Comment by Josh5** [comment]
Sorry I cannot help here. We peasants over here are not allowed to purchase a steam deck.
