### ISSUE TITLE
Change to Windows Image?

### ISSUE THREAD

**Issue by vertex** [Steam-Headless/docker-steam-headless#100]
### Is your feature request related to a problem?

nope

### What is your feature request?

More games would be compatible if this was based on a Windows image, which are available:
https://hub.docker.com/_/microsoft-windows-base-os-images

I know this changes a bit, but I was wondering if this is something you'd consider at all

no biggie if not, much props for a useful tool!

**Comment by Josh5** [comment]
Have you ever used a Windows docker image? Did you read through the link you posted?

This is not possible. It will not work.

**Comment by ahmadnassri** [comment]
might be an option with: https://github.com/dockur/windows/

**Comment by Josh5** [comment]
> might be an option with: https://github.com/dockur/windows/

It's still just a container that runs a virtual machine. It's not running windows in a docker container.

**Comment by cwilby** [comment]
KVM adds non-insignificant IO overhead (CPU/RAM/GPU/Disks) that reduces available resources, but the end result would be compatibility with older games.  Makes sense to build as another project.
