### ISSUE TITLE
[Bug]: Steam not loading

### ISSUE THREAD

**Issue by Jaydenha09** [Steam-Headless/docker-steam-headless#101]
### Describe the Bug

I dont know why it didnt load

### Screenshots

[Screencast from 2023-11-01 19-03-51.webm](https://github.com/Steam-Headless/docker-steam-headless/assets/98650905/da636bf6-e54a-4651-bb5a-82656b5f5159)

### Version

Latest

### Platform

OS: Ubuntu 23.04 x86_64 
Kernel: 6.2.0-36-generic
CPU: Intel i3-8130U (4) @ 3.400GHz
GPU: Intel UHD Graphics 620
Docker version 24.0.5, build 24.0.5-0ubuntu1~23.04.1

**Comment by Josh5** [comment]
This is not a bug with steam headless. If you need support getting Steam Headless working on your hardware, follow the correct support channels.
