### ISSUE TITLE
Enable DLSS with Nvidia Cards

### ISSUE THREAD

**Issue by ApfelBirneKreis** [Steam-Headless/docker-steam-headless#103]
### Is your feature request related to a problem?

Currently on my 3060 and the latest steam headless i can not enable dlss

### What is your feature request?

Enable DLSS functionality with nvidia cards

**Comment by alansari** [comment]
If you are using unRAID you can just add it to the template. The key would be PROTON_ENABLE_NVAPI and value 1. Portainer, yacht, or compose, add it to the stack.env or .env file.  Again I strongly recommend against this. Just use proton-ge and enable it for the games that require it.

**Comment by ApfelBirneKreis** [comment]
Worked :)
