### ISSUE TITLE
TrueNAS Scale Update

### ISSUE THREAD

**Issue by WillKirkmanM** [Steam-Headless/docker-steam-headless#105]
### Is your feature request related to a problem?

[Steam-Headless](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwij-YnW6c-CAxWTUqQEHWmlBckQFnoECA0QAQ&url=https%3A%2F%2Fartifacthub.io%2Fpackages%2Fhelm%2Ftruecharts%2Fsteam-headless&usg=AOvVaw3EXhU0srg_Rv6fZASruiVr&opi=89978449) states that it is still on version 0.0.5. Is this equal to the current version, 0.2.0?

I am currently facing NVENC GPU issues although my GPU supports it and thought an update would solve the issue. The GPU is detected when running `nvidia-smi` along with an up to date GPU driver version. 

### What is your feature request?

.

### Are there any workarounds?

.

### Additional Context

.

**Comment by alansari** [comment]
Still having this issue with the 0.0.6 version? Just jumped on truecharts to give this a go, so havn't tried 0.0.5, but seems like nvenc is working without issue here

**Comment by WillKirkmanM** [comment]
**0.06** Fixed the issue with Nvidia NVENC not being detected

**NOTE**: If you want to access Sunshine Web UI from outside or your client machine make sure to add your NIC:

![image](https://github.com/Steam-Headless/docker-steam-headless/assets/98240335/ed8315c7-f3a6-4132-92be-29721a76a7ec)

I have found that when using Moonlight, my mouse and keyboard are **not** responding in sunshine.
