### ISSUE TITLE
[Bug]: Sunshine not working 

### ISSUE THREAD

**Issue by Bortus-AI** [Steam-Headless/docker-steam-headless#112]
### Describe the Bug

Loads up and I can login but can't connect. In the logs I see 
[2023:11:29:12:05:40]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2023:11:29:12:05:40]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2023:11:29:12:05:40]: Error: Failed to create client: Daemon not running
[2023:11:29:12:05:40]: Info: Configuration UI available at [https://localhost:47990]

### Version

Build: [2023-11-25 02:36:37] [master] [6cc9f56155f3c7f9fc6bc9c22ef2cbf555029c00] [debian]

### Platform

Debian GNU/Linux - 12 (bookworm)
6.1.0-13-amd64 unknown unknown GNU/Linux
| NVIDIA-SMI 545.23.08 Driver Version: 545.23.08 CUDA Version: 12.3 |
Docker version 20.10.24+dfsg1, build 297e128
Docker Compose version v2.21.0

**Comment by Bortus-AI** [comment]
Well still have the error but I was able to finally connect after a reboot so we can close this if its not a real issue

**Comment by alansari** [comment]
"Error: Failed to create client: Daemon not running" can be ignored, it is regarding avahi-daemon.

**Comment by Bortus-AI** [comment]
Gotcha thanks. Now I just need to figure out why my games keep getting corrupted. Pretty sure it's a steam thing and not the docker. Thanks for the help
