### ISSUE TITLE
[Bug]: [ /etc/cont-init.d/60-configure_gpu_driver.sh: executing... ] ... **** Found NVIDIA device 'Please also try adding directory that contains libnvidia-ml.so to your system PATH.' ****   

### ISSUE THREAD

**Issue by danimauden** [Steam-Headless/docker-steam-headless#114]
### Describe the Bug

Hi,

I tried running the docker compose privileged, setting the variables to use the Nvidia GPU (GTX 1050Ti) but the pod keeps rebooting and gives this error: 

[ /etc/cont-init.d/10-setup_user.sh: executing... ]
**** Configure default user ****
  \- Setting default user uid=1000(default) gid=1000(default)
usermod: no changes
  \- Adding default user to any additional required device groups
  \- Adding user 'default' to group: 'video'
  \- Adding user 'default' to group: 'audio'
  \- Adding user 'default' to group: 'input'
  \- Adding user 'default' to group: 'pulse'
  \- Adding user 'default' to group: 'kvm' for device: /dev/input/event0
  \- Setting umask to 000
  \- Create the user XDG_RUNTIME_DIR path '/tmp/.X11-unix/run'
  \- Setting ownership of all log files in '/home/default/.cache/log'
  \- Setting root password
  \- Setting user password
DONE

[ /etc/cont-init.d/11-setup_sysctl_values.sh: executing... ]
**** Configure some system kernel parameters ****
  \- The vm.max_map_count is already greater than '524288'
DONE

[ /etc/cont-init.d/30-configure_dbus.sh: executing... ]
**** Configure container dbus ****
  \- Container configured to run its own dbus
DONE

[ /etc/cont-init.d/30-configure_udev.sh: executing... ]
**** Configure udevd ****
  \- Disable udevd - /run/udev does not exist
  \- Enable dumb-udev service
  \- Ensure the default user has permission to r/w on input devices
DONE

[ /etc/cont-init.d/40-setup_locale.sh: executing... ]
**** Configure local ****
  \- Locales already set correctly to us_US.UTF-8 UTF-8
DONE

[ /etc/cont-init.d/50-configure_pulseaudio.sh: executing... ]
**** Configure pulseaudio ****
  \- Enable pulseaudio service.
  \- Configure pulseaudio to pipe audio to a socket
DONE

[ /etc/cont-init.d/60-configure_gpu_driver.sh: executing... ]
\**** No Intel device found \****
\**** No AMD device found \****
\**** **Found NVIDIA device 'Please also try adding directory that contains libnvidia-ml.so to your system PATH.'** \****
  \- Downloading driver vfind

the log ends there and the pod continues to restart.

Maybe I am doing something wrong?

### Relevant Settings

I already have a container with Plex Server that vents HW acceleration through the nvidia GPU, so I know that per se the system is set up to properly use this resource

### Version

Build: [2023-12-02 02:37:16] [master] [6cc9f56155f3c7f9fc6bc9c22ef2cbf555029c00] [debian]

### Platform

- Distribution: Debian GNU/Linux 11 (bullseye) - (OpenMediaVault)
- Linux Kernel: 6.1.0-0.deb11.13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1~bpo11+1 (2023-10-08) x86_64 GNU/Linux
- GPU Driver version: NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4    
- Docker: Docker version 24.0.7, build afdd53b
- Docker Compose: Docker Compose version v2.21.0

**Comment by Josh5** [comment]
Possibly an idsue with your nvidia setup on the host. I need more information. Have you tested that nvidia-smi workis in the nvidia container runtime on any image?

**Comment by dexd85** [comment]
Good morning,
I do have the same behavior, but in my Case "60-configure_gpu_driver.sh" tries to install NVIDIA driver v525.147.05:
[...]
[ /etc/cont-init.d/60-configure_gpu_driver.sh: executing... ]
**** No Intel device found ****
**** No AMD device found ****
**** Found NVIDIA device 'NVIDIA GeForce RTX 3060 Ti' ****
  - Installing NVIDIA driver v525.147.05 to match what is running on the host

End then it ends up as **danimauden** discribed.

I did now test the Nvidia setup of Container-Toolkit with the sample CUDA container:

```
sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
Fri Dec 15 07:56:22 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:2B:00.0 Off |                  N/A |
|  0%   43C    P8    17W / 225W |      1MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
--> Seems to work fine...any idea?!

**Platform in my case**
Distribution: Debian GNU/Linux 11 (bullseye) - (OpenMediaVault)
Linux Kernel: 5.4.0-150-generic x86_64 GNU/Linux
GPU Driver version: NVIDIA-SMI 525.147.05 Driver Version: v525.147.05 CUDA Version: 12.0
Docker: Docker version 24.0.2, build cb74dfc

Thanks in advance for feedback!
