### ISSUE TITLE
[Bug]: Steam crached on truenas scale

### ISSUE THREAD

**Issue by xe5700** [Steam-Headless/docker-steam-headless#120]
### Describe the Bug

I modify docker image try to running on Truenas scale with docker-compose, desktop is working, but steam is crashed.

[crash_20231230213434_4.zip](https://github.com/Steam-Headless/docker-steam-headless/files/13798190/crash_20231230213434_4.zip)
My repo : https://github.com/xe5700/docker-steam-headless-truenas-scale-nvidia

[logs.zip](https://github.com/Steam-Headless/docker-steam-headless/files/13798217/logs.zip)

### Steps to Reproduce

1. Run steam

### Screenshots

![image](https://github.com/Steam-Headless/docker-steam-headless/assets/9338143/a704fcdf-34bb-4784-8461-fc3424ec57c6)

### Relevant Settings

version: '3.8'
services:
  steam-headless:
    image: truenas-steam-headless:debian
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    # NETWORK:
    #network_mode: host
    networks:
      - default
      - web
    hostname: truenas-steam
    extra_hosts:
      - "truenas-steam:127.0.0.1"
    # DEVICES:
    devices:
      # Use the host fuse device.
      - /dev/fuse
      # Add the host uinput device.
      - /dev/uinput
      # Add AMD/Intel HW accelerated video encoding/decoding devices (optional)
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-modeset
      - /dev/nvidia-caps/nvidia-cap1
      - /dev/nvidia-caps/nvidia-cap2
      
      #- /dev/dri/renderD128
    # Ensure container access to devices 13:*
    device_cgroup_rules:
      - 'c 13:* rmw'
      - 'c 195:* rmw'
      - 'c 240:* rmw'
      - 'c 237:* rmw'

    # VOLUMES:
    volumes:
      #- /var/run/dbus:/run/dbus:ro
      #- /var/run/dbus:/var/run/dbus:ro
      # The location of your home directory.
      - /storage/steam-headless/data:/home/default/:rw

      # The location where all games should be installed.
      # This path needs to be set as a library path in Steam after logging in.
      # Otherwise, Steam will store games in the home directory above.
      # The Xorg socket. This will be shared with other containers so they can access the X server.
      # Select only one option or leave commented out to not share the Xorg socket with any other Docker containers.
      #   Option #1) Start a X server in the container to share with any other containers.
      #- /opt/container-data/steam-headless/.X11-unix/:/tmp/.X11-unix/:rw
      #   Option #2) Use an existing X server running on the host.
      #- /tmp/.X11-unix/:/tmp/.X11-unix/:rw
      #- /tmp/.X11-unix/:/tmp/.X11-unix/:rw
      # Pulse audio socket. This will be shared with other containers so they can access the audio sink.
      # Leave commented out to not share the pulse socket with any other Docker containers.
      #- /opt/container-data/steam-headless/pulse/:/tmp/pulse/:rw
    environment:
      NVIDIA_DRIVER_VERSION: ${NVIDIA_DRIVER_VERSION}
      TZ: ${TZ}
      NAME: ${NAME}
      STEAM_ARGS: ${STEAM_ARGS}

networks:
  default:
  web:
    name: web_default
    external: true

### Version

Build: [2023-12-30 02:37:43] [master] [6cc9f56155f3c7f9fc6bc9c22ef2cbf555029c00] [debian]

### Platform

OS: TrueNAS-SCALE-22.12.4.2
Kernel: 5.15.131+truenas
GPU Driver version: 515.65.01
Host Docker: 20.10.18
Docker compose pod docker: 23.0.1
compose: v2.16.0
GPU hardware: Nvidia CMP-40HX

**Comment by xe5700** [comment]
Maybe because of steam cannot detect resolution, I also cannot start lutris.
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying

(lutris:2): dbind-WARNING **: 14:29:54.456: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
2023-12-31 14:29:54,573: Command 'fluidsynth' not found on your system
2023-12-31 14:29:55,263: Starting Lutris 0.5.14
2023-12-31 14:29:55,266: Using NVIDIA drivers 515.65.01 for x86_64
2023-12-31 14:29:55,266: GPU: NVIDIA CMP 40HX
2023-12-31 14:29:55,266: GPU: 10DE:1F0B 1043:8804 (nvidia drivers)
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/gui/application.py", line 310, in do_activate
    self.window = LutrisWindow(application=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/gui/lutriswindow.py", line 126, in __init__
    self.sidebar.initialize_rows()
  File "/app/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 440, in initialize_rows
    self.update_rows()
  File "/app/lib/python3.11/site-packages/lutris/gui/widgets/sidebar.py", line 527, in update_rows
    self.installed_runners = [runner.name for runner in runners.get_installed()]
                                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/runners/__init__.py", line 101, in get_installed
    runner = import_runner(runner_name)()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/runners/__init__.py", line 83, in import_runner
    runner_module = get_runner_module(runner_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/runners/__init__.py", line 75, in get_runner_module
    return __import__("lutris.runners.%s" % runner_name, globals(), locals(), [runner_name], 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/runners/atari800.py", line 19, in <module>
    class atari800(Runner):
  File "/app/lib/python3.11/site-packages/lutris/runners/atari800.py", line 79, in atari800
    "choices": get_resolutions(),
               ^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/runners/atari800.py", line 12, in get_resolutions
    screen_resolutions = [(resolution, resolution) for resolution in display.DISPLAY_MANAGER.get_resolutions()]
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/graphics/xrandr.py", line 172, in get_resolutions
    return get_resolutions()
           ^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/lutris/util/graphics/xrandr.py", line 102, in get_resolutions
    resolution_list = ['%dx%d' % (DEFAULT_RESOLUTION_WIDTH, DEFAULT_RESOLUTION_HEIGHT)]
                       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: %d format: a real number is required, not str
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/gui/application.py", line 699, in do_command_line
    self.window.present()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'present'

(lutris:2): Gtk-WARNING **: 14:29:55.766: Creating a portal monitor failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Inhibit” on object at path /org/freedesktop/portal/desktop
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/lutris/style_manager.py", line 77, in _call_cb
    values = obj.call_finish(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop (19)

**Comment by Josh5** [comment]
I think i need a little bit more info.
How are you setting up compose on scale? Does this not use k8s?

**Comment by xe5700** [comment]
> I think i need a little bit more info. How are you setting up compose on scale? Does this not use k8s?

I use this https://github.com/truecharts/charts/tree/master/charts/stable/docker running docker in k8s, then use this docker instance running this project.

**Comment by xe5700** [comment]
@Josh5 I try to use truenas K3S version steam-headless, I modify scripts install NVIDIA driver by manual, then gpu acceleration and steam link works. But    lots of games cannot detected monitor, sunshine also not working. Maybe Nvidia CMP series GPU cannot to connect virtual monitor on linux.
![image](https://github.com/Steam-Headless/docker-steam-headless/assets/9338143/01044a09-86b5-4926-8040-87bc1fafa7a2)

I also try use dummy GPU to use 40HX to rendering, it works, but very low fps. Palworld with medium setting (1080P) only 10fps.
