### ISSUE TITLE
[Bug]: lutris install no longer works

### ISSUE THREAD

**Issue by h4de5** [Steam-Headless/docker-steam-headless#21]
### Describe the Bug

when installing lutris and restarting the container, the following error appears in the logs.

```
The following packages have unmet dependencies:
 lutris : Depends: gir1.2-webkit2-4.1 but it is not installable
          Recommends: python3-evdev but it is not going to be installed
          Recommends: gvfs-backends
          Recommends: libwine-development but it is not installable
          Recommends: winetricks but it is not going to be installed
```

I also found that work around online: 
https://www.reddit.com/r/linuxquestions/comments/zatlba/comment/izgxmzc/?utm_source=reddit&utm_medium=web2x&context=3

doing this (by removing the part from the `/home/default/init.d/install_lutris.sh`), lutris did install and I was able to run it.

    echo "deb http://download.opensuse.org/repositories/home:/strycore/Debian_10/ ./" | tee /etc/apt/sources.list.d/lutris.list 

### Steps to Reproduce

1. connect to the x desktop of steam-headless container using vnc
2. click on install lutris from the menü
3. restart container
4. show docker log from starting container
5. lutris is not installed in the container

### Expected Behavior

lutris should be available after the documented steps

### Version

josh5/steam-headless:latest

### Platform

Distribution: Slackware 15.0 (Linux 5.19.17-Unraid x86_64
Linux Kernel: 5.19.17-Unraid
GPU Driver versions: NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     
Docker: Docker version 20.10.21, build baeda1f
Docker-compose: -

### Relevant log output

```Shell
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 lutris : Depends: gir1.2-webkit2-4.1 but it is not installable
          Recommends: python3-evdev but it is not going to be installed
          Recommends: gvfs-backends
          Recommends: libwine-development but it is not installable
          Recommends: winetricks but it is not going to be installed
```

**Comment by Josh5** [comment]
Lutris should now be installed from the "Software" app in the menu. This will install the Flatpak.
