### ISSUE TITLE
[Bug]: AMD drivers not properly installed

### ISSUE THREAD

**Issue by QuaiGoner** [Steam-Headless/docker-steam-headless#22]
### Describe the Bug

Using noVNC i was trying to call vainfo on my AMD APU - but got an error:
(no driver)
![image](https://user-images.githubusercontent.com/41058180/210405190-26103798-7f7d-4fa7-bc63-dd92a619a989.png)
after calling apt update && apt install -y mesa-*
and vainfo --display drm --device /dev/dri/renderD128
i get a proper output
![image](https://user-images.githubusercontent.com/41058180/210404965-3edd7886-9b6f-4ba9-b499-17d6828619e8.png)

but with vainfo its still
![image](https://user-images.githubusercontent.com/41058180/210405187-5dd42431-51c8-40e5-a2a0-057bd62e71b7.png)

### Steps to Reproduce

1. docker compose up -d
2. vainfo
3. apt updatee && apt install -y mesa-*
4. vainfo --display drm --device /dev/dri/renderD128
5. vainfo

### Expected Behavior

AMD driver works and sunshine uses Encoding propperly

### Version

latest

### Platform

Ubuntu 22.04
5.15.0-56-generic x86_64 x86_64 GNU/Linux
Docker version 20.10.22, build 3a2c30b
Docker Compose version v2.14.1

**Comment by Grarak** [comment]
I had the same problem. You can solve it by either not using sid for the mesa driver (https://github.com/Steam-Headless/docker-steam-headless/blob/master/overlay/etc/cont-init.d/60-configure_gpu_driver.sh#L148C5-L148C5), or do `apt upgrade` after adding it as source.

**Comment by Josh5** [comment]
> I had the same problem. You can solve it by either not using sid for the mesa driver (https://github.com/Steam-Headless/docker-steam-headless/blob/master/overlay/etc/cont-init.d/60-configure_gpu_driver.sh#L148C5-L148C5), or do `apt upgrade` after adding it as source.

What packages are being upgraded?

**Comment by alansari** [comment]
To get hardware encoding on amd I just needed to update va-driver-all and libva2 from Sid. Temporarily it works by creating an init.d script with apt update and install for the two packages. After the container is up and running apt still sources the Sid repos so no need to add it to the sources.

**Comment by Bu156** [comment]
> To get hardware encoding on amd I just needed to update va-driver-all and libva2 from Sid. Temporarily it works by creating an init.d script with apt update and install for the two packages. After the container is up and running apt still sources the Sid repos so no need to add it to the sources.

This makes Steam (in Docker) crash for me whenever initiating a stream

**Comment by timsmithxyz** [comment]
Seeing the same with a dedicated AMD GPU. Can confirm downgrading all packages to bookworm fixes acceleration in Sunshine and Steam streaming.

**Comment by cRaZy-bisCuiT** [comment]
Do we have a solution here? I'm using steam-headless with a Cezanne APU which works pretty perfect with it. Except for steam is not doing HW encoding, even though it's turned on.

Installing `libva2:i386` will fix `vainfo` but steam is still doing S/W encoding. How could I fix that?

**Comment by cRaZy-bisCuiT** [comment]
The following Docker Image (upstream) fixes the issue, since Debian Sid is made optional:

- docker pull josh5/steam-headless:debian

For me Sunshine HW encoding and Steam HW encoding works.

**Comment by cRaZy-bisCuiT** [comment]
@QuaiGoner Can you confirm this? If so, maybe @Josh5  could close the issue then. Solved by 12a498e1eba2dab5abfed484c22742ed14ce4e8e
