### ISSUE TITLE
Are there no installation instructions?

### ISSUE THREAD

**Issue by AnotherNeko** [Steam-Headless/docker-steam-headless#24]
### Description

On lines 100 and 101 of [run_server.sh](https://github.com/Steam-Headless/docker-steam-headless/blob/master/devops/run_server.sh), I get the error 
```
Error response from daemon: No such container: steam-s
Error: No such container: steam-s
```
every time I run the script as sudo.
I think this is because there's no step in the installation instructions to actually download/install/build/something-else the docker container.
Is there a complete documentation to go from a fresh install of any debian/ubuntu-based OS -> install docker using Docker's instructions -> "install"/download this git repo -> configure the /opt/container-services/steam-headless/.env file-> ?????? -> Steam running inside a docker container?

**Comment by AnotherNeko** [comment]
one of the steps is to run the command `sudo docker build -t docker-steam-headless ." in the folder "docker-steam-headless` (which is a product of running `git clone https://github.com/Steam-Headless/docker-steam-headless.git`

**Comment by AnotherNeko** [comment]
I want to use the Host X server as directed:

"""USING HOST X SERVER:

If your host is already running X, you can just use that. To do this, be sure to configure:

    DISPLAY=:0
    (Variable) - Configures the sceen to use the primary display. Set this to whatever your host is using
    MODE=secondary
    (Variable) - Configures the container to not start an X server of its own
    HOST_DBUS=true
    (Variable) - Optional - Configures the container to use the host dbus process
    /run/dbus:/run/dbus:ro
    (Mount) - Optional - Configures the container to use the host dbus process
"""

But the [Dockerfile](https://github.com/Steam-Headless/docker-steam-headless/blob/master/Dockerfile#L559)(line 559) and [run_server.sh](https://github.com/Steam-Headless/docker-steam-headless/blob/master/devops/run_server.sh#L122)(line 122) are both hardcoded to use DISPLAY=:55 ??? 

How do I /or/ do I need to change this in every file where it occurs?

**Comment by AnotherNeko** [comment]
don't use `docker-compose`, use `docker compose`

**Comment by AnotherNeko** [comment]
"""[you can generate a script inside the ~/init.d directory ending with ".sh". This will be executed on the container startup.](https://github.com/Steam-Headless/docker-steam-headless#additional-software)"""

if this script is corrupted, then there is no way to start the docker without it, and the container will be stuck in "restarting" state. There doesn't seem to be any way to edit this file without finishing the restart, which it can't finish.

**Comment by Josh5** [comment]
Not sure exactly when this lines up with this issue, but here are the docs:
https://github.com/Steam-Headless/docker-steam-headless/blob/master/README.md#installation
