### ISSUE TITLE
[Bug]: Big Picture Mode invisible

### ISSUE THREAD

**Issue by dcflachs** [Steam-Headless/docker-steam-headless#26]
### Describe the Bug

When launched in Big Picture Mode the steam interface is not visible. The desktop is inaccessible as steam seams to have focus and the mouse or controller is in its window. Moving around the mouse makes sounds seeming to indicated that big picture is running just not visible.

### Steps to Reproduce

1. Open the Steam interface.
2. Click View -> Big Picture Mode
3.  Big Picture Mode appears in the task bar but is not visible.

### Expected Behavior

Big Picture Mode should open.

### Screenshots

![image](https://user-images.githubusercontent.com/11656775/219907378-3e1ee1b8-2642-4264-90f6-d23aa07828d2.png)

### Version

Build: [2023-02-18 02:56:11] [master] [9b962580ff02f02dcd8239166f9d1ab6cae188bd]

### Platform

- UNRAID
- 5.10.28-Unraid
- No nvidia driver
- Docker version 20.10.5, build 55c4c88

**Comment by Nicroin** [comment]
Fixed mine by updating my GPU drivers

**Comment by dcflachs** [comment]
I am not sure that is an option in my case. I am running this docker without GPU acceleration.

**Comment by Josh5** [comment]
Should be now fixed in latest build. Re-open this issue if it is not.
