### ISSUE TITLE
'/usr/bin/start-udev.sh' is not executable

### ISSUE THREAD

**Issue by bsaurusrex** [Steam-Headless/docker-steam-headless#3]
'/usr/bin/start-udev.sh' is not executable

This error is thrown when running with MODE=secondary env.

**Comment by Josh5** [comment]
This should be fixed very soon (if not already).

I'm considering retiring secondary mode in the not-to-distant future. This week we will be able to run multiple secondary instances of steam inside the Steam Headless container. Once this is published, I will at some point in the not-to-distant future, I will probably remove the "secondary" mode and withdraw the templates from the Unraid CA.
