### ISSUE TITLE
Add KasmVNC

### ISSUE THREAD

**Issue by Matheus-Garbelini** [Steam-Headless/docker-steam-headless#34]
### What is your feature request?

Is it possible to support [KasmVNC](https://github.com/kasmtech/KasmVNC) instead of only novnc?
The reason is that kasmvnc has a gaming mode to grab the mouse and it's possible to add this image directly as a streamed container to [Kasm Workspaces](https://www.kasmweb.com/) and launch this container very easily for any user

**Comment by Josh5** [comment]
Would this also support audio?

**Comment by EtienneK** [comment]
Yes, KASM supports audio

**Comment by Josh5** [comment]
> Yes, KASM supports audio

No it does not:
https://github.com/kasmtech/KasmVNC/issues/31

KasmVNC (which @Matheus-Garbelini would like added to this project) will not support audio. Only Kasm Workspaces does. If you want Kasm Workspaces, then you need to use Kasm Workspaces. 

I have set KasmVNC up in Steam Headless (took a few hours) only to find it is pretty average an experience and no better than noVNC. This is not how you want to be playing video games guys.
