### ISSUE TITLE
Modify Refresh Rate

### ISSUE THREAD

**Issue by coxde** [Steam-Headless/docker-steam-headless#38]
### What is your feature request?

Thanks for your amazing work! Is is possible to change the maximum refresh rate? Now it's only allowed to set as 60 Hz.

**Comment by Josh5** [comment]
Have you tried opening the "Settings > Display" app? This lets me set it to 120Hz.
![image](https://github.com/Steam-Headless/docker-steam-headless/assets/8370197/250ef3f9-5030-406e-816b-2bf1206dc139)

**Comment by mikedebian** [comment]
Hey, I am sorry to comment on this closed issue, however, I have a problem with this and I am unable to figure out what to do. Whenever in VNC or in Moonlight, I get the DUMMY0 output, running at 50hz 1080p.

I have passed on a RX 580 GPU running HDMI out to a 3440x1440 display, in which the HDMI can output 100hz.
I can not get it to see the display, at all.
Running secondary mode or primary mode, X11 host or in docker container it does not matter.

**Comment by LordPatoVonDuck** [comment]
Same issue here Sept 24th 2026 : Can modify resolution, but no refresh rate. All games are capped at 50fps and choppy

<img width="569" height="373" alt="Image" src="https://github.com/user-attachments/assets/01894c3a-619c-4859-bb93-6ebc270fed25" />
