### ISSUE TITLE
[Bug]: No GPU Found, when using Arc A380 (Or Any Arc i would imagine)

### ISSUE THREAD

**Issue by karbowiak** [Steam-Headless/docker-steam-headless#39]
### Describe the Bug

The bug is that no Intel GPU is found at startup, when not running an Intel CPU - and having an Arc GPU (in this case A380)

A possible fix could be here https://github.com/Steam-Headless/docker-steam-headless/blob/master/overlay/etc/cont-init.d/60-configure_gpu_driver.sh#L20

Instead of `lscpu | grep 'Model name:' | grep -i intel | cut -d':' -f2 | xargs`

Use something like..

`lspci | grep -i "VGA compatible controller: Intel" | cut -d':' -f3 | xargs`

Should yield:
`Intel Corporation DG2 [Arc A380] (rev 05)` from `2f:00.0 VGA compatible controller: Intel Corporation DG2 [Arc A380] (rev 05)`

### Steps to Reproduce

1. Have an Arc GPU (A380, A750, A770..)

### Expected Behavior

Working similarly to nVidia / AMD

### Screenshots

![image](https://github.com/Steam-Headless/docker-steam-headless/assets/337661/c0c74903-b03b-49c7-8a43-e22d27fd42bf)

### Version

Build: [2023-05-13 02:41:17] [master] [9b962580ff02f02dcd8239166f9d1ab6cae188bd]

### Platform

UnRAID 6.12.0-rc5

### Relevant log output

```Shell
none
```

**Comment by Josh5** [comment]
Yup! That is a good fix. Could you submit a PR for that?
