### ISSUE TITLE
[Bug]: No mouse or keyboard with Sunshine / Moonlight

### ISSUE THREAD

**Issue by nierdal** [Steam-Headless/docker-steam-headless#43]
### Describe the Bug

The mouse or keyboard will not respond on Sunshine / Moonlight. They do work however with noVNC & Steam Remote.

Using the lastest docker update, and I have the ENABLE_SUNSHINE:true variable and ENABLE_EVDEV_INPUTS:true.

### Steps to Reproduce

1. Open Moonlight on OSX
2. Connect to desktop with the following settings : 1440p and 120hz.
3. See the desktop
4. Mouse or keyboard will not respond with Moonlight

### Expected Behavior

Mouse or keyboard work on Moonlight

### Relevant Settings

- I'm using Moonlight 4.3.1 on a Mac M1 with OSX Ventura 13.4
- Using a Nvidia Geforce 3090 RTX with a dummy displayport dongle connected.
- Mouse or keyboard are connected to the Unraid computer, but most of the time attached to a Ubuntu VM.

### Version

5746f6ad0f97

### Platform

Unraid OS 6.11.5

**Comment by nierdal** [comment]
Also tested with a Windows 11 client with the same problem. It does not seems to be a moonlight client problem.

**Comment by tbal82** [comment]
Same problem here (Unraid OS 6.12.1)

Any news ?

**Comment by Josh5** [comment]
> Same problem here (Unraid OS 6.12.1)
> 
Plese try again with a fresh install and install Sunshine from the software store.

**Comment by tbal82** [comment]
Solved the issue by setting the container network to Host. I then saw that it was documented, but what if I want to use a secondary container ?

**Comment by Josh5** [comment]
> Solved the issue by setting the container network to Host. I then saw that it was documented, but what if I want to use a secondary container ?

Then you are going to need to use a macvlan for the second container
