### ISSUE TITLE
[Bug]: Uncompressing nvidia driver

### ISSUE THREAD

**Issue by stuCONNERS1983** [Steam-Headless/docker-steam-headless#53]
### Describe the Bug

I'm stuck uncompressing the NVidia driver. It worked great until last nights changes.
The log says:
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 470.182.03.........................................

Terminal is stuck in a loop, with the following message:
**** Found NVIDIA device 'NVIDIA GeForce GTX 1050 Ti' ****
steam-steam-headless-1  | Installing NVIDIA driver v470.182.03 to match what is running on the host
steam-steam-headless-1 exited with code 1

This results in the container being unable to start.

### Steps to Reproduce

1, .env created
2, docker-compose.yml created
3, docker-compose up command issued
4, stuck at steam-steam-headless-1  | Installing NVIDIA driver v470.182.03 to match what is running on the host
steam-steam-headless-1 exited with code 1

### Expected Behavior

How the container to boot into steam.

### Version

master

### Platform

Debian 11
5.19.17-2-pve:
 NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4
Docker version 24.0.4, build 3713ee1

### Relevant log output

```Shell
steam-steam-headless-1  | usermod: no changes
steam-steam-headless-1  | Adding default user to video, audio, input and pulse groups
steam-steam-headless-1  | Adding default user to any additional required device groups
steam-steam-headless-1  | Adding user 'default' to group: 'systemd-resolve' for device: /dev/input/event0
steam-steam-headless-1  | Adding user 'default' to group: 'video' for device: /dev/dri/card1
steam-steam-headless-1  | Adding user 'default' to group: 'input' for device: /dev/dri/renderD129
steam-steam-headless-1  | Setting umask to 000
steam-steam-headless-1  | Create the user XDG_RUNTIME_DIR path '/tmp/.X11-unix/run'
steam-steam-headless-1  | Adding default home directory template
steam-steam-headless-1  | Setting ownership of all log files in '/home/default/.cache/log'
steam-steam-headless-1  | Setting root password
steam-steam-headless-1  | Setting user password
steam-steam-headless-1  | DONE
steam-steam-headless-1  |
steam-steam-headless-1  | [ /etc/cont-init.d/20-configre_sshd.sh: executing... ]
steam-steam-headless-1  |
steam-steam-headless-1  | **** Configure SSH server ****
steam-steam-headless-1  | Disable SSH server
steam-steam-headless-1  | DONE
steam-steam-headless-1  |
steam-steam-headless-1  | [ /etc/cont-init.d/30-configure_dbus.sh: executing... ]
steam-steam-headless-1  |
steam-steam-headless-1  | **** Configure container dbus ****
steam-steam-headless-1  | Container configured to run its own dbus
steam-steam-headless-1  | DONE
steam-steam-headless-1  |
steam-steam-headless-1  | [ /etc/cont-init.d/30-configure_udev.sh: executing... ]
steam-steam-headless-1  |
steam-steam-headless-1  | **** Configure container to run udev management ****
steam-steam-headless-1  | **** Ensure the default user has permission to r/w on input devices ****
steam-steam-headless-1  | DONE
steam-steam-headless-1  |
steam-steam-headless-1  | [ /etc/cont-init.d/40-setup_locale.sh: executing... ]
steam-steam-headless-1  |
steam-steam-headless-1  | **** Locales already set correctly to en_US.UTF-8 UTF-8 ****
steam-steam-headless-1  | DONE
steam-steam-headless-1  |
steam-steam-headless-1  | [ /etc/cont-init.d/50-configure_pulseaudio.sh: executing... ]
steam-steam-headless-1  |
steam-steam-headless-1  | **** Configure pulseaudio ****
steam-steam-headless-1  | Configure pulseaudio to pipe audio to a socket
steam-steam-headless-1  | DONE
steam-steam-headless-1  |
steam-steam-headless-1  | [ /etc/cont-init.d/60-configure_gpu_driver.sh: executing... ]
steam-steam-headless-1  |
steam-steam-headless-1  | **** Found NVIDIA device 'NVIDIA GeForce GTX 1050 Ti' ****
steam-steam-headless-1  | Installing NVIDIA driver v470.182.03 to match what is running on the host
```

**Comment by Josh5** [comment]
How do you have docker onstalled? And also how is the nvidia container runtime installed?

**Comment by stuCONNERS1983** [comment]
The runtime is via the nvidia docker2 container. Docker is installed as OpenMediaVault extras. My other docker containers are still up and working fine.

If I update to the unstable drivers for debian 11, I believe its 512, this container installs the drivers but failed on sunshine. And exits with a fatal error.

I did a fresh install today of my os, it still failed at the exact same place  its worked great for weeks

**Comment by stuCONNERS1983** [comment]
Fixed this error, i changed to a newer nvidia driver. this problem has now gone.
