### ISSUE TITLE
[Bug]: Unable to install games into /mnt/games mounted Docker volume

### ISSUE THREAD

**Issue by tnielsen2** [Steam-Headless/docker-steam-headless#57]
### Describe the Bug

Problem: The container cannot write to the `/mnt/games` Docker volume mount, although permissions appear correct.

Upon fresh install of the container using docker-compose, everything works except the /mnt/games folder is not visible in the Steam client. 

After following the troubleshooting steps [here](https://github.com/Steam-Headless/docker-steam-headless/blob/master/docs/troubleshooting.md), I was then able to see the games folder named: "Mounted Games", but unable to read/write to the folder, being met with the following error: 

`An error occurred while installing <game>: "disk write error"`

### Steps to Reproduce

1. `sudo docker stop <container>`
2. `sudo docker rm <container>`
3. `sudo docker rmi <image>`
4. `cd /opt/container-data/steam-headless/home`
5. `sudo rm -rf ~/.local/share/flatpak`
6. `cd /opt/container-services/steam-headless`
7. `sudo docker-compose up -d --force-recreate`

### Expected Behavior

Being able to install games to the volume mount. 

### Screenshots

![image](https://github.com/Steam-Headless/docker-steam-headless/assets/21163004/31611620-2c13-40bc-a028-43713f50d16a)
![image](https://github.com/Steam-Headless/docker-steam-headless/assets/21163004/91cfbef2-9b73-4008-988a-02688124752d)
![image](https://github.com/Steam-Headless/docker-steam-headless/assets/21163004/676a337f-920a-4cfa-b178-ade878ac3eeb)
![image](https://github.com/Steam-Headless/docker-steam-headless/assets/21163004/ae97eedd-8ac2-465c-a9b9-750856f94aa2)

### Relevant Settings

- default docker compose file as per [here](https://github.com/Steam-Headless/docker-steam-headless/blob/master/docs/compose-files/docker-compose.default.yml). 
- ext4 file system for /mnt/games
- Host /mnt/ permissions (user trent is 1000:1000):
```
trent@dell-e:/mnt$ ll
total 12
drwxr-xr-x  3 root  root  4096 Jul  9 19:19 ./
drwxr-xr-x 22 root  root  4096 Jul 10 14:18 ../
drwxrwxrwx  4 trent trent 4096 Jul 10 13:12 games/
```
- Host games folder (and recursive) permissions:
```
trent@dell-e:/mnt/games$ ll
total 16
drwxrwxrwx 4 trent trent 4096 Jul 10 13:12 ./
drwxr-xr-x 3 root  root  4096 Jul  9 19:19 ../
drwxrwxrwx 3 trent trent 4096 Jul  9 19:59 GameLibrary/
```

docker-compose relevant mount config:

```
    # VOLUMES:
    volumes:
      # The location of your home directory.
      - /opt/container-data/steam-headless/home/:/home/default/:rw
      # The location where all games should be installed.
      # This path needs to be set as a library path in Steam after logging in.
      # Otherwise, Steam will store games in the home directory above.
      - /mnt/games/:/mnt/games/:rw
      # Input devices used for mouse and joypad support inside the container.
      - /dev/input/:/dev/input/:ro
      # The Xorg socket. This will be shared with other containers so they can access the X server.
      - /opt/container-data/steam-headless/.X11-unix/:/tmp/.X11-unix/:rw
      # Pulse audio socket. This will be shared with other containers so they can access the audio sink.
      - /opt/container-data/steam-headless/pulse/:/tmp/pulse/:rw
      # Store dind var files in a volume
      - steam-headless-var-lib-docker:/var/lib/docker/:rw
      # Store flatpak var files in a volume
      - steam-headless-var-lib-flatpak:/var/lib/flatpak/:rw
```

### Version

Build: [2023-07-10 08:33:45] [master] [3be80a920e0ca242e71562f959bcad9155fd43cf] [debian]

### Platform

- Ubuntu - 22.04.1 LTS (Jammy Jellyfish)
- 5.15.0-76-generic x86_64 x86_64 GNU/Linux
- | NVIDIA-SMI 525.125.06 Driver Version: 525.125.06 CUDA Version: 12.0 |
- Docker version 24.0.4, build 3713ee1
- docker-compose version 1.29.2, build unknown

### Relevant log output

```Shell
No logs found in docker logs, and I was unable to see/find any logs in the steam app when attempting a game install.
```

**Comment by tnielsen2** [comment]
As a troubleshooting step, I have tried completely removing all folders within the /mnt/games folder, to see what happened.
The container recreated the `GameLibrary/SteamLibrary` folders and also recreated the `libraryfolder.vdf` file, but the problem still exists.

**Comment by Josh5** [comment]
> PR submitted to address this. LMK if you have any better idea/way to accomplish this. 

Legend
