### ISSUE TITLE
[Bug]: Sunshine is broken

### ISSUE THREAD

**Issue by sfxworks** [Steam-Headless/docker-steam-headless#58]
### Describe the Bug

Sunshine no longer works with the latest image

root@epyc-gigabyte:/home/default/.cache/log# cat sunshine.err.log 
/usr/bin/start-sunshine.sh: line 43: sunshine: command not found
/usr/bin/start-sunshine.sh: line 43: sunshine: command not found
/usr/bin/start-sunshine.sh: line 43: sunshine: command not found
/usr/bin/start-sunshine.sh: line 43: sunshine: command not found
/usr/bin/start-sunshine.sh: line 43: sunshine: command not found
/usr/bin/start-sunshine.sh: line 43: sunshine: command not found
/usr/bin/start-sunshine.sh: line 43: sunshine: command not found
/usr/bin/start-sunshine.sh: line 43: sunshine: command not found
/usr/bin/start-sunshine.sh: line 43: sunshine: command not found
/usr/bin/start-sunshine.sh: line 43: sunshine: command not found

### Steps to Reproduce

Enable sunshine

### Expected Behavior

Sunshine starts

### Version

3be80a920e0ca242e71562f959bcad9155fd43cf

### Platform

your latest version

**Comment by sfxworks** [comment]
For reference I rebuilt it against the branch just before my k8s pr and it starts up fine. Not sure somewhere along the way it got removed and I dont see it in the deb docker build file

**Comment by stuCONNERS1983** [comment]
Have you tried setting sunshine to false in .env file. Using vnc on http://[ServerIP]:8083 and setting up sunshine in there? That's what I've had yo do.

**Comment by Josh5** [comment]
Sunshine is installed via flatpak. If it is not there, grab it from the software app via VNC

**Comment by Josh5** [comment]
I need to delete that `start-sunshine.sh` file

**Comment by alansari** [comment]
Anyone having trouble with sunshine flatpak, just install flatseal and mirror the permissions given to steam.  Solved the problem with it finding encoders.  Might also want to add --device=dri to both steam and sunshine if you have an igpu and want to use it for encoding.

**Comment by stuCONNERS1983** [comment]
> For reference I rebuilt it against the branch just before my k8s pr and it starts up fine. Not sure somewhere along the way it got removed and I dont see it in the deb docker build file

How did you do this?

**Comment by sfxworks** [comment]
> Sunshine is installed via flatpak. If it is not there, grab it from the software app via VNC

I really liked the ability to not have to use anything but moonlight and jump right in. Is there a plan to reenable the auto install of sunshine?

**Comment by Josh5** [comment]
> > Sunshine is installed via flatpak. If it is not there, grab it from the software app via VNC
> 
> I really liked the ability to not have to use anything but moonlight and jump right in. Is there a plan to reenable the auto install of sunshine? 

Im readding this for you this week...
