### ISSUE TITLE
[Bug]: No Audio in Sunshine

### ISSUE THREAD

**Issue by stuCONNERS1983** [Steam-Headless/docker-steam-headless#59]
### Describe the Bug

There is no audio in sunshine. The audio works fine if i connected via vnc. 

### Steps to Reproduce

Load container using default settings
Connect via moonlight
Video is fine, No audio.
Log confirms no audio will be used

### Expected Behavior

Audio to be used

### Relevant Settings

#  ____            _                 
# / ___| _   _ ___| |_ ___ _ __ ___  
# \___ \| | | / __| __/ _ \ '_ ` _ \ 
#  ___) | |_| \__ \ ||  __/ | | | | |
# |____/ \__, |___/\__\___|_| |_| |_|
#        |___/                       
# 
NAME='SteamHeadless'
TZ='Europe/London'
USER_LOCALES='en_US.UTF-8 UTF-8'
DISPLAY=':55'
SHM_SIZE='2G'

##                      using an NVIDIA GPU, set this to 'nvidia' for anything else, set this to 'runc'.
DOCKER_RUNTIME='nvidia'

#  ____        __             _ _     _   _               
# |  _ \  ___ / _| __ _ _   _| | |_  | | | |___  ___ _ __ 
# | | | |/ _ \ |_ / _` | | | | | __| | | | / __|/ _ \ '__|
# | |_| |  __/  _| (_| | |_| | | |_  | |_| \__ \  __/ |   
# |____/ \___|_|  \__,_|\__,_|_|\__|  \___/|___/\___|_|   
#                                                         
# 
PUID='1000'
PGID='1000'
UMASK='000'
USER_PASSWORD='libreelec'

#  ____                  _               
# / ___|  ___ _ ____   _(_) ___ ___  ___ 
# \___ \ / _ \ '__\ \ / / |/ __/ _ \/ __|
#  ___) |  __/ |   \ V /| | (_|  __/\__ \
# |____/ \___|_|    \_/ |_|\___\___||___/
#                                        
#
# Mode
##                      Steam Headless container running in 'primary' mode.
MODE='primary'

# Web UI
##      Description:    Configures the WebUI to use for accessing the virtual desktop.
WEB_UI_MODE='vnc'
##      Description:    Enables audio over for the VNC Web UI if 'WEB_UI_MODE' is set to 'vnc'.
ENABLE_VNC_AUDIO='true'
##      Description:    Configure the port to use for the WebUI.
PORT_NOVNC_WEB='8083'
##      Description:    Configure nat1to1 for the neko WebUI if it is enabled by setting 'WEB_UI_MODE' to 'neko'. This will need to be the IP address of the host.
NEKO_NAT1TO1=''

# Sunshine
##      Description:    Enable Sunshine streaming service.
ENABLE_SUNSHINE='false'
##      Description:    Set the Sunshine service username.
#SUNSHINE_USER='admin'
##      Description:    Set the Sunshine service password.
#SUNSHINE_PASS='admin'

# Xorg
##      Description:    Enable Keyboard and Mouse Passthrough. This will configure the Xorg server to catch all evdev events for Keyboard, Mouse, etc.
ENABLE_EVDEV_INPUTS='true'

# Nvidia specific config (not required for non Nvidia GPUs)
##      Description:    Controls which driver libraries/binaries will be mounted inside the container.
NVIDIA_DRIVER_CAPABILITIES='all'
##      Description:    Controls which GPUs will be made accessible inside the container.
NVIDIA_VISIBLE_DEVICES='all'

---
services:
  steam-headless:
    image: josh5/steam-headless:latest
    restart: unless-stopped
    runtime: nvidia
    ## NOTE: Requires privileged access to host to be able to access the required devices
    privileged: true
    shm_size: ${SHM_SIZE}
    ipc: host # Could also be set to 'shareable'
    ulimits:
      nofile:
        soft: 1024
        hard: 524288

    # NETWORK:
    ## NOTE:  Steam headless always requires the use of the host network.
    ##        If we do not use the host network, then device input is not possible
    ##        and your controllers will not work in steam games.
    network_mode: host
    hostname: ${NAME}
    extra_hosts:
      - "${NAME}:127.0.0.1"
    
    # ENVIRONMENT:
    ## Read all config variables from the .env file
    env_file: .env

    # VOLUMES:
    volumes:
      # The location of your home directory.
      - /srv/dev-disk-by-uuid-bbea844e-d179-4ab4-bd2e-0cff7dfc1414/steam/home/:/home/default/:rw
      # The location where all games should be installed.
      # This path needs to be set as a library path in Steam after logging in.
      # Otherwise, Steam will store games in the home directory above.
      - /srv/dev-disk-by-uuid-0650f0a0-14fa-4db3-a677-e6aac7d40cfa/Games/:/mnt/games/:rw
      # Input devices used for mouse and joypad support inside the container.
      - /dev/input/:/dev/input/:ro
      # The Xorg socket. This will be shared with other containers so they can access the X server.
      - /srv/dev-disk-by-uuid-bbea844e-d179-4ab4-bd2e-0cff7dfc1414/steam/.X11-unix/:/tmp/.X11-unix/:rw
      # Pulse audio socket. This will be shared with other containers so they can access the audio sink.
      - /srv/dev-disk-by-uuid-bbea844e-d179-4ab4-bd2e-0cff7dfc1414/steam/pulse/:/tmp/pulse/:rw
      # Store dind var files in a volume
      - steam-headless-var-lib-docker:/var/lib/docker/:rw
      # Store flatpak var files in a volume
      - steam-headless-var-lib-flatpak:/var/lib/flatpak/:rw

volumes:
  steam-headless-var-lib-docker:
  steam-headless-var-lib-flatpak:

### Version

master

### Platform

Debian GNU/Linux - 11 (bullseye)
 5.19.17-2-pve
 NVIDIA-SMI 525.116.04   Driver Version: 525.116.04   CUDA Version: 12.0
Docker version 24.0.4, build 3713ee1

### Relevant log output

```Shell
[2023:07:11:13:35:46]: Error: Couldn't connect to pulseaudio: Access denied
[2023:07:11:13:35:46]: Warning: There will be no audio
[2023:07:11:13:35:46]: Error: Unable to initialize audio capture. The stream will not have audio.
```

**Comment by stuCONNERS1983** [comment]
Fixed. Took about 10 installs before it worked.

**Comment by stuCONNERS1983** [comment]
Nope, Ive literally changes operating system. Sound works for the initial install after reboot then fails. Tried it on debian 11 and ubuntu 22.04. Sounds fine on vnc. Sound survived after two reboots but then disappeared

**Comment by stuCONNERS1983** [comment]
To add some more information. I've discovered on first boot, the sunshine audio sink works. If I stop the container amd start it again, There is no sunshine sink.

If the container is stopped, and the container removed via portainer, using docker compose to rebuild the image using all existing files, sound returns, until a reboot. Does anyone have a fix for this?

**Comment by Epsylon42** [comment]
I have the same problem. Worked around it by manually building an older image (from 3be80a920e0ca242e71562f959bcad9155fd43cf if i remember correctly)

**Comment by stuCONNERS1983** [comment]
How did you do that? Mines been broken for a week.

**Comment by Epsylon42** [comment]
Ah, nevermind. I just checked it and it doesn't work. I think it was rebuilding an image that helped, as you said

**Comment by survivor182ca** [comment]
I have the same problem as you guy. It used to work well on the old dockerfile based on bulleye

**Comment by survivor182ca** [comment]
It seems to be a user / permission problems?

**Comment by Josh5** [comment]
Is this still an issue?

**Comment by Epsylon42** [comment]
Just pulled the new commits, built a new image, and did the same steps as before. Seems to work fine for me - no sound issues
