### ISSUE TITLE
reemo.io for streaming

### ISSUE THREAD

**Issue by vishalkadam47** [Steam-Headless/docker-steam-headless#69]
### What is your feature request?

An alternative to any vnc connect or game streaming can we add reemo https://reemo.io/download
pre-installed reemo and by just add an option to enter personal key which would automatically display the running node in our reemo dashboard account

please have a look its free for individuals this would be best streaming platform to use

**Comment by Josh5** [comment]
Looks like they do not support Debian Bookworm. They also look like they will require systemd and since they do not have any source or anything for me to work with here, there is no way for me to support this. Sorry.
