### ISSUE TITLE
Some examples of scripts for installing software at startup

### ISSUE THREAD

**Issue by p5-f20w18k** [Steam-Headless/docker-steam-headless#74]
### Description

“If you wish to install additional applications, you can generate a script inside the ~/init.d directory ending with ".sh". This will be executed on the container startup.”

Are there any examples of how this would look? I am not familiar with Debian, and I can’t find anything in the documentation.

**Comment by alansari** [comment]
Any bash script would work. An example that auto updates yuzu early access on container startup would be: 
-------------------
#!/bin/bash

YUZU_PATH=/home/default/Applications/yuzu.AppImage

curl -s https://api.github.com/repos/pineappleEA/pineapple-src/releases/latest | jq -r ".assets[0] | .browser_download_url" | wget -qO $YUZU_PATH -i -

chmod +x $YUZU_PATH
-------------------

**Comment by alansari** [comment]
This is being worked on, though you can start using it from now:
https://github.com/Steam-Headless/init.d

**Comment by p5-f20w18k** [comment]
Sorry I completely forgot about opening this, will join discord to ask any questions going forward :)
