### ISSUE TITLE
[Bug]: NVIDIA Driver v470 fails to install due to incorrect parameter name

### ISSUE THREAD

**Issue by Kickball** [Steam-Headless/docker-steam-headless#76]
### Describe the Bug

The name of the parameter for not installing the kernel modules for the NVIDIA drivers changed between versions 470 and 535.

```
root# /tmp/NVIDIA.run -A | grep no-kernel && /tmp/NVIDIA.run -v | grep version
  --no-kernel-modules
  --no-kernel-module-source
nvidia-installer:  version 535.98

root# ./NVIDIA_470.199.02.run -A | grep no-kernel && ./NVIDIA_470.199.02.run -v | grep version
  --no-kernel-module
  --no-kernel-module-source
nvidia-installer:  version 470.199.0
```

The script has `--no-kernel-modules` hardcoded ([here](https://github.com/Steam-Headless/docker-steam-headless/blob/d2b4d2cae792a6446de1e0a88fc2d7ab1631354f/overlay/etc/cont-init.d/60-configure_gpu_driver.sh#L69)) which causes it to fail for drivers v470 with the following log message:
```
root# cat steam/Downloads/nvidia_gpu_install.log 
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux 470.199.02..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
./nvidia-installer: unrecognized option: "--no-kernel-modules"

ERROR: Invalid commandline, please run `./nvidia-installer --help` for usage information.
```

### Steps to Reproduce

1. Install the Nvidia Driver plugin for unraid. Selecting v470.199.02 as the preferred driver version.
2. Install the docker-steam-headless container leaving everything as the default other than the mounts and the extra parameters.
3. Adjust the extra parameters to add `--runtime=nvidia`
4. Run the container and obseve it crash looping with no logs. Review the logs in `$(Appdata)/Downloads/nvidia_gpu_install.log` and observe the error about the incorrect/unknown parameter.

### Version

Build: [2023-08-06 03:07:36] [master] [d2b4d2cae792a6446de1e0a88fc2d7ab1631354f] [debian]

### Platform

Distribution: Slackware v15.0.
Kernel: 6.1.38-Unraid Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz GenuineIntel GNU/Linux
GPU Drivers: NVIDIA-SMI 470.199.02   Driver Version: 470.199.02   CUDA Version: 11.4
Docker version 20.10.24, build 297e128

### Relevant log output

```
....
**** Found NVIDIA device 'NVIDIA 660' ****
Downloading driver v470.199.02 to match what is running on the host
# script then crashes with no further docker logs
```

### Related Reports

https://forums.unraid.net/topic/118390-support-josh5-steam-headless/?do=findComment&comment=1198242

**Comment by Josh5** [comment]
Should now be resolved in latest builds
