### ISSUE TITLE
Add more options to container: disable vnc, no virtual screen in xorg

### ISSUE THREAD

**Issue by chaitan3** [Steam-Headless/docker-steam-headless#8]
The container should have the following options:
1. Disable vnc
2. Disable or modify steam autostart
3. Disable virtual screen, so that hdmi dummy plugs or physical screens can be used.

**Comment by Josh5** [comment]
We should already have point 3 as default behaviour. If you were to run steam headless with a dummy plug or a monitor plugged into the host, it should start up an X server configured to pass that desktop out to that monitor.

I have tested this with both Intel accelerated desktop and with a NVIDIA GPU and both work as expected. The external monitor or dummy is detected and read for possible screen resolutions. If you plug in a monitor, you should see it. However, at this point in time, you will not be able to control it with the host keyboard/mouse.

**Comment by Josh5** [comment]
Also, point 1, you can already disable VNC in the new neko branch by setting 'WEB_UI_MODE' to anything other than 'vnc' or 'neko'. I would advertise this to be set as either ['vnc', 'neko', 'none'] where setting WEB_UI_MODE=none will disable any WebUI. This will be merged in the coming weeks

**Comment by bladyle** [comment]
> We should already have point 3 as default behaviour. If you were to run steam headless with a dummy plug or a monitor plugged into the host, it should start up an X server configured to pass that desktop out to that monitor.
> 
> I have tested this with both Intel accelerated desktop and with a NVIDIA GPU and both work as expected. The external monitor or dummy is detected and read for possible screen resolutions. If you plug in a monitor, you should see it. However, at this point in time, you will not be able to control it with the host keyboard/mouse.

I'm running my Unraid server on laptop and when I run the container, Steam uses the laptop monitor. I want to access it from different device and don't want to initialize the laptop monitor. What is the proper way to run the container without using the monitor but still have remove VNC?
