### ISSUE TITLE
[Bug]: Steam window won't open in container

### ISSUE THREAD

**Issue by jeprecated** [Steam-Headless/docker-steam-headless#80]
### Describe the Bug

I was able to login, but the window never came up afterwards. Now I cannot open the steam window. It's running, I can interact with the menu in the top right bar. I can even install games via the mobile app, and run them remotely on another pc. But I cannot open the window to change the settings or install games manually!

### Steps to Reproduce

1. Run container on Unraid
2. Open container
3. Login to steam

That's all 🤷 

### Expected Behavior

I can open the window.

### Screenshots

![image](https://github.com/Steam-Headless/docker-steam-headless/assets/1471350/2e50eef3-78e5-4937-9822-634af3fce06a)
 
Click button ->

![image](https://github.com/Steam-Headless/docker-steam-headless/assets/1471350/0a3c92e7-d291-4988-b546-f2877d76d19e)

### Relevant Settings

Just the standard docker settings

```
docker run
  -d
  --name='steam-headless'
  --net='host'
  --privileged=true
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="TheBox"
  -e HOST_CONTAINERNAME="steam-headless"
  -e 'USER_PASSWORD'='[PASSWORD]'
  -e 'TZ'='Europe/Copenhagen'
  -e 'USER_LOCALES'='en_US.UTF-8 UTF-8'
  -e 'WEB_UI_MODE'='vnc'
  -e 'NVIDIA_VISIBLE_DEVICES'='all'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='all'
  -e 'DISPLAY'=':55'
  -e 'MODE'='primary'
  -e 'PORT_NOVNC_WEB'='8083'
  -e 'ENABLE_VNC_AUDIO'='false'
  -e 'ENABLE_EVDEV_INPUTS'='false'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8083]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/Josh5/docker-steam-headless/master/images/steam-icon.png'
  -v '/mnt/user/appdata/steam-headless':'/home/default':'rw'
  -v '/mnt/user/MiscMedia/Games/Steam':'/mnt/games':'rw'
  --hostname='SteamHeadless'
  --add-host='SteamHeadless:127.0.0.1'
  --restart=unless-stopped
  --shm-size=2G
  --ipc="host"
  -v '/tmp/.X11-unix':'/tmp/.X11-unix':'rw'
  -v '/tmp/tmp/pulse':'/tmp/tmp/pulse':'rw'
  -v '/dev/input':'/dev/input':'ro'
  --ulimit nofile=1024:524288 'josh5/steam-headless:latest'
37ebdf771e5a08dc53c6b63df007fd697a767a30dc71f6fc0b719a22d8544706
```

### Version

Build: [2023-08-19 02:34:59] [master] [d2b4d2cae792a6446de1e0a88fc2d7ab1631354f] [debian]

### Platform

- Slackware - 15.0
- 5.19.17-Unraid 12th Gen Intel(R) Core(TM) i5-12500 GenuineIntel GNU/Linux
- Docker version 20.10.21, build baeda1f
- Docker Compose version v2.17.3
    - Instructions say `docker compose -v` but it was actually `docker compose version`
- 01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290/390] (rev 80) (prog-if 00 [VGA controller])
        Subsystem: Micro-Star International Co., Ltd. [MSI] Hawaii PRO [Radeon R9 290/390]
        Flags: bus master, fast devsel, latency 0, IRQ 155, IOMMU group 16
        Memory at 4000000000 (64-bit, prefetchable) [size=256M]
        Memory at 4010000000 (64-bit, prefetchable) [size=8M]
        I/O ports at 7000 [size=256]
        Memory at 86100000 (32-bit, non-prefetchable) [size=256K]
        Expansion ROM at 86140000 [disabled] [size=128K]
        Capabilities: [48] Vendor Specific Information: Len=08 <?>
        Capabilities: [50] Power Management version 3
        Capabilities: [58] Express Legacy Endpoint, MSI 00
        Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
        Capabilities: [150] Advanced Error Reporting
        Capabilities: [200] Physical Resizable BAR
        Capabilities: [270] Secondary PCI Express
        Capabilities: [2b0] Address Translation Service (ATS)
        Capabilities: [2c0] Page Request Interface (PRI)
        Capabilities: [2d0] Process Address Space ID (PASID)
        Kernel driver in use: radeon
        Kernel modules: radeon, amdgpu
     - AMD GPU instead of NVIDIA

**Comment by ohare93** [comment]
On a refresh of the container, it is now stuck here:

![image](https://github.com/Steam-Headless/docker-steam-headless/assets/1471350/d157be57-d4c2-44bb-ad3f-80c37e86d06b)

**Comment by Josh5** [comment]
Could you please try again with the latest build and get back to me?

Thanks

**Comment by ohare93** [comment]
Same issue.

It seems this is an issue some get with Steam https://github.com/ValveSoftware/steam-for-linux/issues/9769#issuecomment-1666923257 and is perhaps related to GPUs? Does it matter that I have an AMD GPU? Does one require a GPU to run this container at all?

**Comment by ohare93** [comment]
Deleted my config and did a fresh install. Same issue after login - stuck on "Loading user data" 🤷‍♂️

**Comment by colingoodman** [comment]
Piggy backing onto this issue to say that I recently did a fresh install on an ubuntu server and I am having this exact issue. Steam is woefully unresponsive, but I have no issues with the rest of the desktop environment out of the box.

**Comment by Josh5** [comment]
Try opening steam's settings and disabling he acceleration for the webui stuff.

**Comment by ohare93** [comment]
> Try opening steam's settings and disabling he acceleration for the webui stuff.

Well I can't open Steam at all 🤷‍♂️ hitting settings similarly does nothing

**Comment by Josh5** [comment]
> > Try opening steam's settings and disabling he acceleration for the webui stuff.
> 
> Well I can't open Steam at all 🤷‍♂️ hitting settings similarly does nothing

This is with the latest build. Could you try wiping the appdata, pulling the image and starting fresh.

**Comment by Little709** [comment]
I also have this issue. 

![image](https://github.com/Steam-Headless/docker-steam-headless/assets/21006524/37d05561-d675-451f-b4f5-8919b46303ba)

It can open the settings menu, just not the steam interface.. I also run the containter on unraid

**Comment by ohare93** [comment]
> > > Try opening steam's settings and disabling he acceleration for the webui stuff.
> > 
> > 
> > Well I can't open Steam at all 🤷‍♂️ hitting settings similarly does nothing
> 
> This is with the latest build? Could you try wiping the appdata, pulling the image and starting fresh.

Cleared my appdata, pulled latest image, rebuild the container: same issue 🤷

**Comment by Josh5** [comment]
> > > > Try opening steam's settings and disabling he acceleration for the webui stuff.
> > > 
> > > 
> > > Well I can't open Steam at all 🤷‍♂️ hitting settings similarly does nothing
> > 
> > This is with the latest build? Could you try wiping the appdata, pulling the image and starting fresh.
> 
> Cleared my appdata, pulled latest image, rebuilt the container: same issue 🤷 

And you can not open the settings from the task icon menu?

**Comment by ohare93** [comment]
That was the only way I could try to do so. Nothing opened 🤷

**Comment by williamhelle** [comment]
Same issue, on NoVNC the window stuck at 800x900 px resolution and I don't know how to expand, when I try the "expand to the window" or fullscreen nothing change and the window of the screen is stuck on 800x900 px.

I don't know but the host have latest driver for Nvidia GPUs and the container seem working so I understand that the driver work too in the container but same problem as :

> On a refresh of the container, it is now stuck here:
> 
> ![image](https://user-images.githubusercontent.com/1471350/262338227-d157be57-d4c2-44bb-ad3f-80c37e86d06b.png)

In this image the render of the background of steam just don't work correctly, but we can still interact with them, and settings window work just fine and I can setup Steam link normally like another computer running steam, so to test if steam link worked I configure it and start streaming, work fine too, but no Big Picture is showing (just the title of the window "Steam Big Picture" in the taskbar but no interface nothing graphically visible, just sound and a stream of the desktop environnement)
 I try to repull the container but no still not working, I do some modification with portainer and hope this won't brake the apt directory and no same, still not having the correct screen resolution and problem with steam, so I tried to run RimWorld and wow this work ! For a second and crash.
 I doesn't have more idea to make it work and I don't find some Wiki or Documentation about resizing a desktop environnement of steam-headless container just the docs of xfce4 and vnc are existing for me.
 
 Did someone have any idea or solution to fix this problem ?
 Thanks

**Comment by williamhelle** [comment]
![image](https://github.com/Steam-Headless/docker-steam-headless/assets/27297709/29899492-b376-4754-b028-ae1e02242f1f)
I try to install Nvidia Driver in the container using "docker exec -it steam-headless /bin/bash" (sudo if you are not in the docker group) or with the terminal emulator through novnc and I can't install :

nvidia-driver
   nvidia-kernel-dkms
   nvidia-kernel-dkms-525.125.06
 
But I was able to install :
   libcuda1
nvidia-driver-bin
nvidia-driver-libs

then I restart all and the problem wasn't fixed and steam still literally being transparent (menu still working fine and same as other window that steam Desktop and steam BigPicture mode)

**Comment by williamhelle** [comment]
Just fond something in the log container :
![image](https://github.com/Steam-Headless/docker-steam-headless/assets/27297709/3e07bb58-a54b-45a5-a537-d0b8ad5eb02a)

I think this is a part of some problem, but i don't know why does it can't see nvidia gpu, all driver are installed on host and container ?

**Comment by williamhelle** [comment]
For some reasons Big Picture Launched and work just fine, this always appends when I start RimWorld First and then it start BigPicture a few moments after RimWorld or at the same time :

This is what I've got :
![image](https://github.com/Steam-Headless/docker-steam-headless/assets/27297709/473b963e-9fda-4f49-8094-f062adefb8ff)
![image](https://github.com/Steam-Headless/docker-steam-headless/assets/27297709/49e6bd7b-aa16-4727-b647-fdee1995fe6c)
![image](https://github.com/Steam-Headless/docker-steam-headless/assets/27297709/f98fff48-b803-4895-8865-6c44ca65b870)
At the third picture RimWorld already started in background so I stop the game by using Steam Link app interface and this stop the stream, then I try to only start BP mode but this append :

![image](https://github.com/Steam-Headless/docker-steam-headless/assets/27297709/e7689b62-8f99-4d3c-90df-1be4c4830ac9)

So i was able to start RimWorld and close it and I saw few seconds the interface working at the background before the stream close.

To launch the game I use preLaunch Buttons on steam link like below :
![image](https://github.com/Steam-Headless/docker-steam-headless/assets/27297709/3805894d-7993-4de9-869c-72d44849cff5)

Don't take note of the poor wifi/connection, this don't change nothing (i'm on the local network)


See you later

**Comment by ohare93** [comment]
Well I fixed my problem, but in a rather extreme way 😅 

So beforehand, when I made this issue, I had an AMD GPU installed and I had the Radeon TOP plugin as per the instructions. 

I have just today switched for an NVIDIA GPU, and added `--gpus all --runtime nvidia` into the extra parameters in this container in Unraid.

On rebooting, everything seemed to work! Not only that, but my screensize over VNC was much larger.

I don't see "Just get an NVIDIA GPU" as a fix for most people here, but perhaps the fact that this works for me now can help someone debug this 🤷‍♂️

**Comment by Josh5** [comment]
Doesn't help me as i don't have an AMD GPU unfortunately.

**Comment by Josh5** [comment]
Im closing this as no one contributing to this project (mostly just myself) has an AMD GPU so there is no way to investigate this further.

**Comment by Uklosk** [comment]
I have an AMD GPU and have this problem, I'm willing to contribute but won't have much time to investigate until next week.
