### ISSUE TITLE
[Bug]: Mtu issues when using ubisoft games

### ISSUE THREAD

**Issue by 21st-centuryman** [Steam-Headless/docker-steam-headless#87]
### Describe the Bug

we should add a line to the scripts that changes the mtu to 1500. For some reason ubisoft connect will not work unless this value is setup. This is quite common on the steam deck as well

https://steamcommunity.com/app/1675200/discussions/0/3789255198744319602/
https://www.reddit.com/r/SteamDeck/comments/v6bbcn/cant_get_ubisoft_connect_games_working/

I am not sure if this is a arch only issue or if its the same on debian

### Steps to Reproduce

1. Start a ubisoft game on steam
2. fail to login since you will not be abel to connect

### Version

master

### Platform

I do not think this will be relevant

**Comment by Josh5** [comment]
This is probably something you should modify on the host, not inside a docker container.
