### ISSUE TITLE
Run Steam without GPU acceleration by default

### ISSUE THREAD

**Issue by will2hew** [Steam-Headless/docker-steam-headless#91]
### Is your feature request related to a problem?

When there is either no GPU available, or incorrectly configured GPU drivers, Steam attempts to run with GPU acceleration and then hangs on the "Loading User Data" screen. This is a documented bug in the steam-for-linux repo, see [here](https://github.com/ValveSoftware/steam-for-linux/issues/9769). 

I believe this is likely the same issue experienced in #80

The error can be reproduced by running docker-steam-headless on a new VM, without a GPU.

### What is your feature request?

Given the expected use for this project, where people will be using VNC to install games and then using game streaming to actually play, the performance of the Steam app inside the container doesn't seem critical.

Therefore, I suggest we run steam with `-cef-disable-gpu` by default, which will mitigate this issue in the interim. Keen to hear what you think of the suggestion and am happy to make a PR if the suggestion is accepted.  

### Are there any workarounds?

Running Steam with `-cef-disable-gpu` will fix this issue for people in the interim.

**Comment by Josh5** [comment]
I think this is not that helpful. People can already add these if they wish. Perhaps just documenting it in the compose templates would be better.
