### ISSUE TITLE
webRTC

### ISSUE THREAD

**Issue by vishalkadam47** [Steam-Headless/docker-steam-headless#97]
### What is your feature request?

is there a possibility to get webRTC or kasmVNC which has webRTC already included, for a better performance instead of noVNC

**Comment by Josh5** [comment]
Im looking into it. Already have a project for this. No we will not be using kasm.

**Comment by vishalkadam7** [comment]
that's nice happy to hear that you have a project, particularly kasm is not a choice I'm just looking for a better performance with webRTC,
